export const categories = [
  {
    name: 'Pizza',
  },
  {
    name: 'Snacks',
  },
  {
    name: 'Desserts',
  },
  {
    name: 'Drinks',
  },
  {
    name: 'Sauces',
  },
];

export const _ingredients = [
  {
    id: 1,
    name: 'Italian herbs',
    price: 50,
    imageUrl: '/images/ingredients/italian-herbs.png',
  },
  {
    id: 2,
    name: 'Roasted onion',
    price: 75,
    imageUrl: '/images/ingredients/roasted-onion.png',
  },
  {
    id: 3,
    name: 'Chicken',
    price: 175,
    imageUrl: '/images/ingredients/chicken.png',
  },
  {
    id: 4,
    name: 'Ham',
    price: 180,
    imageUrl: '/images/ingredients/ham.png',
  },
  {
    id: 5,
    name: 'Pepperoni',
    price: 200,
    imageUrl: '/images/ingredients/pepperoni.png',
  },
  {
    id: 6,
    name: 'Bacon',
    price: 200,
    imageUrl: '/images/ingredients/bacon.png',
  },
  {
    id: 7,
    name: 'Jalapeno',
    price: 60,
    imageUrl: '/images/ingredients/jalapeno.png',
  },
  {
    id: 8,
    name: 'Corn',
    price: 70,
    imageUrl: '/images/ingredients/corn.png',
  },
  {
    id: 9,
    name: 'Cherry tomatoes',
    price: 90,
    imageUrl: '/images/ingredients/cherry-tomatoes.png',
  },
  {
    id: 10,
    name: 'Black olives',
    price: 100,
    imageUrl: '/images/ingredients/black-olives.png',
  },
  {
    id: 11,
    name: 'Pineapple',
    price: 80,
    imageUrl: '/images/ingredients/pineapple.png',
  },
  {
    id: 12,
    name: 'Tomatoes',
    price: 70,
    imageUrl: '/images/ingredients/tomatoes.png',
  },
  {
    id: 13,
    name: 'Arugula',
    price: 90,
    imageUrl: '/images/ingredients/arugula.png',
  },
  {
    id: 14,
    name: 'Cheddar',
    price: 220,
    imageUrl: '/images/ingredients/cheddar.png',
  },
  {
    id: 15,
    name: 'Blue cheese',
    price: 250,
    imageUrl: '/images/ingredients/blue-cheese.png',
  },
  {
    id: 16,
    name: 'Parmesan cheese',
    price: 230,
    imageUrl: '/images/ingredients/parmesan-cheese.png',
  },
];


export const products = [
  {
    name: 'Firepie Chicken Melt',
    imageUrl: '/images/snacks/chicken-sandwich.avif',
    size: '1 pc',
    weight: '280 g',
    sauce: 'creamy blaze dip',
    description: 'Toasted sandwich with juicy chicken, smoky bacon, mozzarella, fresh veggies and our signature creamy blaze sauce.',
    categoryId: 2,
  },
  {
    name: 'Green Garden Crunch',
    imageUrl: '/images/snacks/vege-sandwich.avif',
    size: '1 pc',
    weight: '280 g',
    sauce: 'herbal garlic dip',
    description: 'A veggie-packed sandwich with mozzarella, mushrooms, olives, corn, tomatoes, onion and arugula. Fresh and light!',
    categoryId: 2,
  },
  {
    name: 'Firebox Fries',
    imageUrl: '/images/snacks/lunchbox-with-fries.avif',
    size: '1 pc',
    weight: '300 g',
    description: 'Crispy fries with golden chicken wings and spicy seasoning. The perfect box for a quick bite.',
    categoryId: 2,
  },
  {
    name: 'Crunch Box Hash Browns',
    imageUrl: '/images/snacks/lunchbox-with-hash-brown.avif',
    size: '1 pc',
    description: 'Crispy hash browns paired with juicy baked wings and a dip. Comfort food at its best!',
    categoryId: 2,
  },
  {
    name: 'Herby Fire Fries',
    imageUrl: '/images/snacks/french-fries.avif',
    size: '160 g',
    description: 'Oven-baked potato fries tossed in Italian herbs. Crispy and fragrant.',
    categoryId: 2,
  },
  {
    name: 'Smoky Blaze Wings (6 pcs)',
    imageUrl: '/images/snacks/chicken-wings.avif',
    size: '6 pcs',
    weight: '150 g',
    description: 'Tender chicken wings roasted with smoky spices. Juicy, spicy and addictive!',
    categoryId: 2,
  },
  {
    name: 'Berry Bliss Rolls',
    imageUrl: '/images/desserts/rolls-currant.avif',
    size: '16 pcs',
    weight: '280 g',
    description: 'Soft sweet rolls with a mix of berries, served warm with creamy vanilla dip.',
    categoryId: 3,
  },
  {
    name: 'Sunny Pineapple Swirls',
    imageUrl: '/images/desserts/rolls-pineapple.avif',
    size: '16 pcs',
    weight: '340 g',
    description: 'Fluffy rolls filled with pineapple and cinnamon. A tropical dessert dream!',
    categoryId: 3,
  },
  {
    name: 'Velvet Cheesecake',
    imageUrl: '/images/desserts/cheesecake.avif',
    size: '1 pc',
    weight: '150 g',
    description: 'Creamy New York–style cheesecake with a smooth and rich taste.',
    categoryId: 3,
  },
  {
    name: 'Choco Lava Donut',
    imageUrl: '/images/desserts/chocolate-donut.avif',
    size: '1 pc',
    weight: '75 g',
    description: 'Fluffy donut bursting with molten chocolate cream inside.',
    categoryId: 3,
  },
  {
    name: 'Strawberry Cloud Donut',
    imageUrl: '/images/desserts/strawberry-donut.avif',
    size: '1 pc',
    weight: '75 g',
    description: 'Airy donut filled with sweet strawberry cream. Light and dreamy!',
    categoryId: 3,
  },
  {
    name: 'Coca-Cola Classic',
    imageUrl: '/images/drinks/coca-cola.avif',
    size: '0.5 L',
    weight: '500 g',
    description: 'The timeless classic. Refreshing Coca-Cola in a 0.5 L bottle.',
    categoryId: 4,
  },
  {
    name: 'Fanta Spark',
    imageUrl: '/images/drinks/fanta.avif',
    size: '0.5 L',
    weight: '500 g',
    description: 'Bright and fizzy orange Fanta in a 0.5 L bottle.',
    categoryId: 4,
  },
  {
    name: 'Sprite Fresh',
    imageUrl: '/images/drinks/sprite.avif',
    size: '0.5 L',
    weight: '500 g',
    description: 'Crisp and refreshing Sprite in a 0.5 L bottle.',
    categoryId: 4,
  },
  {
    name: 'Vanilla Dream Dip',
    imageUrl: '/images/sauces/vanilla.avif',
    size: '1 pc',
    weight: '40 g',
    description: 'Sweet vanilla dip made for desserts. 40 g portion.',
    categoryId: 5,
  },
  {
    name: 'Classic Tomato Dip',
    imageUrl: '/images/sauces/tomato.avif',
    size: '1 pc',
    weight: '45 g',
    description: 'Rich tomato dip for pizza and snacks. 45 g portion.',
    categoryId: 5,
  },
  {
    name: 'Smoky BBQ Dip',
    imageUrl: '/images/sauces/bbq.avif',
    size: '1 pc',
    weight: '40 g',
    description: 'Sweet and smoky BBQ dip, perfect for wings and pizza. 40 g.',
    categoryId: 5,
  },
  {
    name: 'Golden Honey Mustard Dip',
    imageUrl: '/images/sauces/honey-mustard.avif',
    size: '1 pc',
    weight: '40 g',
    description: 'Sweet-and-savory honey mustard dip. 40 g.',
    categoryId: 5,
  },
  {
    name: 'Garlic Flame Dip',
    imageUrl: '/images/sauces/garlic.avif',
    size: '1 pc',
    weight: '40 g',
    description: 'Creamy garlic dip with a fiery touch. 40 g.',
    categoryId: 5,
  },
  {
    name: 'Red Heat Sriracha Dip',
    imageUrl: '/images/sauces/sriracha.avif',
    size: '1 pc',
    weight: '40 g',
    description: 'Spicy and bold Sriracha-style dip for real heat lovers. 40 g.',
    categoryId: 5,
  },
];

